AWSTemplateFormatVersion: '2010-09-09'
Description: Openstreetmap Stitch Tool (zappa)

Resources:
  IamRoleLambda:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  IamPolicyLambda:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: osm-stitch-production_lambda
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: 'arn:aws:logs:eu-west-1:*:*'
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
            Resource: '*'
      Roles:
        - Ref: IamRoleLambda

Outputs:
  LambdaRole:
    Value:
      Ref: 'IamRoleLambda'
